---Problem : https://www.hackerrank.com/challenges/weather-observation-station-8/problem?isFullScreen=true

---Weather Observation Station 8

---Query the list of CITY names from STATION which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates.

SELECT DISTINCT CITY
FROM STATION
WHERE REGEXP_LIKE(City, '^[AEIOU].*[aeiou]$');